const fs = require("fs");
const path = require("path");
const { runtimeDirectory, writeJsonAtomicSync } = require("../runtime_paths");
const { COMPANY } = require("./world");
const WORK_DIR = runtimeDirectory("shane_work", "shane_work");
const KNOWLEDGE_PATH = path.join(WORK_DIR, "knowledge.json");
function loadKnowledge() { if (!fs.existsSync(KNOWLEDGE_PATH)) return { schema_version: 1, facts: [] }; try { const value = JSON.parse(fs.readFileSync(KNOWLEDGE_PATH, "utf-8")); return value && Array.isArray(value.facts) ? value : { schema_version: 1, facts: [] }; } catch (error) { console.error("Shane Work 读取 knowledge.json 失败:", error.message); return { schema_version: 1, facts: [] }; } }
function saveKnowledge(knowledge) { fs.mkdirSync(WORK_DIR, { recursive: true }); writeJsonAtomicSync(KNOWLEDGE_PATH, knowledge); }
function eventSnapshot(event) { return { equipment_id: event.equipment_id || null, category: event.category || null, severity: event.severity || null, status: event.status || null, result: event.status === "RESOLVED" ? "RESOLVED" : null, resolved_at: event.status === "RESOLVED" ? event.updated_at || null : null }; }
function taskSnapshot(task) { return { equipment_id: task.equipment_id || null, category: task.category || null, status: task.status || null, source_event_id: task.source_event_id || null, completed_at: task.status === "DONE" ? task.completed_at || null : null }; }
function onboardingSnapshot(session) { const context = session.context || {}; return { day: context.day || null, phase: context.phase || null, current_step_id: context.current_step_id || null, current: context.current || null, recent: context.recent || null, next: context.next || null, status: session.status || null }; }
function learnFact(knowledge, subjectType, subject, channel, now) { const id = subjectType === "EVENT" ? subject.event_id : subject.task_id; const factKey = subjectType + ":" + id; const snapshot = subjectType === "EVENT" ? eventSnapshot(subject) : taskSnapshot(subject); const index = knowledge.facts.findIndex(fact => fact.fact_key === factKey); if (index >= 0) { const previous = knowledge.facts[index]; if (JSON.stringify(previous.known_snapshot || {}) === JSON.stringify(snapshot)) return false; knowledge.facts[index] = { ...previous, last_known_at: now, known_snapshot: snapshot }; return true; } knowledge.facts.push({ knowledge_id: "KN-" + String(knowledge.facts.length + 1).padStart(6, "0"), fact_key: factKey, subject_type: subjectType, source_event_id: subjectType === "EVENT" ? id : subject.source_event_id || null, source_task_id: subjectType === "TASK" ? id : null, channel, learned_at: now, last_known_at: now, known_snapshot: snapshot }); return true; }
function learnOnboardingFact(knowledge, session, now) { const factKey = "ONBOARDING:" + session.session_id; const snapshot = onboardingSnapshot(session); const index = knowledge.facts.findIndex(fact => fact.fact_key === factKey); if (index >= 0) { knowledge.facts[index] = { ...knowledge.facts[index], last_known_at: now, known_snapshot: snapshot }; return knowledge.facts[index]; } const fact = { knowledge_id: "KN-" + String(knowledge.facts.length + 1).padStart(6, "0"), fact_key: factKey, subject_type: "ONBOARDING", source_event_id: null, source_task_id: null, source_onboarding_id: session.session_id, channel: "DIRECT_ONBOARDING", learned_at: now, last_known_at: now, known_snapshot: snapshot }; knowledge.facts.push(fact); return fact; }
function learnLocationFact(knowledge, locationId, now, learnedAt = now) { const factKey = "LOCATION_DISCOVERED:" + locationId; const index = knowledge.facts.findIndex(fact => fact.fact_key === factKey); if (index >= 0) return false; const labels = { BREAK_ROOM: "厂内休息室", CAFETERIA: "员工餐厅" }; const snapshot = { location_id: locationId, label: labels[locationId] || locationId }; knowledge.facts.push({ knowledge_id: "KN-" + String(knowledge.facts.length + 1).padStart(6, "0"), fact_key: factKey, subject_type: "LOCATION", source_event_id: null, source_task_id: null, source_location_id: locationId, channel: "DIRECT_LOCATION", learned_at: learnedAt, last_known_at: now, known_snapshot: snapshot }); return true; }
function learnCoreFacilityFact(knowledge, session, now) { const factKey = "ONBOARDING:CORE_FACILITY_AWARENESS"; const index = knowledge.facts.findIndex(fact => fact.fact_key === factKey); if (index >= 0) return false; const completedAt = session?.history?.find(item => item.step_id === "ONBOARDING_COMPLETED")?.occurred_at || now; const snapshot = { label: "生产区域、维修间、仓库、安全出口及主要设备区域的基本划分" }; knowledge.facts.push({ knowledge_id: "KN-" + String(knowledge.facts.length + 1).padStart(6, "0"), fact_key: factKey, subject_type: "FACILITY", source_event_id: null, source_task_id: null, source_onboarding_id: session?.session_id || null, channel: "DIRECT_ONBOARDING", learned_at: completedAt, last_known_at: now, known_snapshot: snapshot }); return true; }
function learnMealBenefitFact(knowledge, session, now) { const factKey = "ONBOARDING:MEAL_BENEFIT_AWARENESS"; const index = knowledge.facts.findIndex(fact => fact.fact_key === factKey); if (index >= 0) return false; const completedAt = session?.history?.find(item => item.step_id === "ONBOARDING_COMPLETED")?.occurred_at || now; const snapshot = { ...COMPANY.meal_service, included: [...COMPANY.meal_service.included] }; knowledge.facts.push({ knowledge_id: "KN-" + String(knowledge.facts.length + 1).padStart(6, "0"), fact_key: factKey, subject_type: "BENEFIT", source_event_id: null, source_task_id: null, source_onboarding_id: session?.session_id || null, channel: "DIRECT_ONBOARDING", learned_at: completedAt, last_known_at: now, known_snapshot: snapshot }); return true; }
module.exports = { loadKnowledge, saveKnowledge, learnFact, learnOnboardingFact, learnLocationFact, learnCoreFacilityFact, learnMealBenefitFact };
